import './globals.css'
import Header from '@/app/Header'

export const metadata = {
  title: 'Hello',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
